---
title: "Getting Started"
author: "Data Science"
date: "`r format(Sys.time(), '%B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# psrccensus

These are instructions on how to use the package psrccensus.


```

### Set up your API key

The first time you run this code, you will need to set our Census API Key as an environment variable, if you haven't done that before. After that you can just get it.
This is the website to get a key: https://api.census.gov/data/key_signup.html. Once you run Sys.setenv on the Census API Key you will only need to run Sys.getenv.


```{r keys, results='hide'}
#Sys.setenv(CENSUS_API_KEY = 'PUT YOUR KEY HERE')
Sys.getenv("CENSUS_API_KEY")
```

Next you need to decide what tables you would like to download. This is the hardest part because you have find the correct table code, decide on geography, and which years.


### 2019 1-year table list
https://api.census.gov/data/2019/acs/acs1/variables.html

### 2015-2019 5 year- table list
https://api.census.gov/data/2019/acs/acs5/variables.html

# Get the data  -----------------------------------------------------
The main function psrc_acs_table has four parameters: tbl_code, geog, yr,acs.

* tbl_code is the code of the ACS table list on the Census website, in string format, such as "B02001_005"

* geog is the geography, currently with the options of "county" or "tract"

* yr is the last numeric year of the data, such as 2019 for 2014-2019 five year, or 2019 for one year

* acs is which dataset you are using, such as "acs1" or "acs5"

You can find the list of ACS datasets available via the api here: https://www.census.gov/data/developers/data-sets.html

THe function to make a table is defined like this: psrc_table(tbl_code, geog, yr,acs)

Here are a few examples of using the function.



```
# Map the data  -----------------------------------------------------
create_tract_map is function in which you send in a data frame by tract, and it makes a map. The parameter is takes in is one ACS variable by tract.

```{r map_data}

```

